### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheAlbert1** [Lukas-Diffner-Persson/Lukas-Diffner-Persson#1]
I noticed some typos in your readme. I hope you take the time to fix them since good grammar adds to your professionalism.
In "About Me", you spelled programming as "Programing", and Polhemsskolan as "Polhemskolan". In "Skills" you spelled socialize as "socelize".

I would also consider writing the email address as johndoe@example dot com instead of johndoe@example.com, because there are bots that crawl the web that look for email addresses to send spam mail to.

Lastly, "I'm lucky" is not a skill. I recommend changing it to something you know you can do, like setting up networks.

**Comment by Lukas-Diffner-Persson** [comment]
I fixed my spelling mistakes, and changed my the email so with no .com so i wont get spam and lastly i changed the "I'm lucky" skill
