### ISSUE TITLE
you suffer from CSFS

### ISSUE THREAD

**Issue by DePhrog** [Lukas-Diffner-Persson/Lukas-Diffner-Persson#2]
you should get at least get one more way of contacting you.
you say "i'm lucky" even though lucky isn't considered to be a skill.
also you have a spelling mistake that's says you are currently learning programing and not programming u should fix that.

-_-_-_-_-_-_-

**Comment by Lukas-Diffner-Persson** [comment]
I respelled programming and changed my "I'm lucky" skill, but I'm not going to add another way of contact because i don't i any more connections that i feel comfortable of sharing.
