### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by An0rring** [Lukas-Diffner-Persson/Lukas-Diffner-Persson#3]
Expand your reach and make it easier for people to connect with you by adding more options. 
"I'm lucky" is not a a skill. 
You spelled programming wrong.

**Comment by Lukas-Diffner-Persson** [comment]
I respelled programming and changed my "I'm lucky" skill, but I'm not going to add another way of contact because i don't i any more connections that i feel comfortable of sharing.
